flowchart TB
    subgraph "Hybrid Integrator"
        direction TB

        f("<b>y(t<sub>k</sub>) = x<sub>c</sub>(t<sub>k</sub>)</b><br/>x<sub>c</sub>(t<sub>k</sub>)/dt<sub>k</sub> = x<sub>d<sub>k</sub></sub><br/>x<sub>d<sub>k</sub></sub> = u(t<sub>k</sub>)")

        u(("u<sub>1</sub>(t)"))
         
        y(("y(t)"))
    end

    u --> f
    
    f --> y
