flowchart LR

    subgraph "Kausal"

        direction LR

        f11["f<sub>1</sub>"] --> f21["f<sub>2</sub>"]

    end

    subgraph "Akausal"

        direction LR

        f12["f<sub>1</sub>"] --- f22["f<sub>2</sub>"]

    end