flowchart

    Konzepte[<b>Fault Analyzer Konzepte</b>]

    Konzepte --> Störung["Störung (<i>Fault</i>)"]
    Konzepte --> Bedingung["Bedingung (<i>Condition</i>)"]
    Konzepte --> Störungssatz["Störungssatz (<i>Fault Set</i>)"]