flowchart LR

    subgraph MIL

        direction LR

        Normal

        Accelerator

    end

    SIL

    PIL

    style Normal fill:lightpink,stroke:red
    style Accelerator fill:lightpink,stroke:red