flowchart

    Assessment --> Sequence-Diagram-Assessment[Sequence<br/>Diagram<br/>Assessment]
    Assessment --> Baseline-Criteria[Baseline<br/>Criteria]
    Assessment --> Logical-and-Temporal-Assessment[Logical and<br/>Temporal<br/>Assessment]
    Assessment --> Custom-Criteria[Custom<br/>Criteria]

    style Assessment fill:white