flowchart LR

    Red[1. Red] --> Green[2. Green] --> Refactor[3. Refactor] --> Red

    style Red fill:LightPink,stroke:red
    style Green fill:lightgreen,stroke:green
    style Refactor fill:lightblue,stroke:blue